app = "turtle-soup-game"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  SPARKAI_APP_ID = "6126ea78"
  SPARKAI_API_SECRET = "OTgxMmNmNjlhNjcxOGI5YTZkZjI5NWZk"
  SPARKAI_API_KEY = "9a551368ad829cf9d47e9cc22716a179"
  SECRET_KEY = "dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"] 