services:
  - type: web
    name: turtle-soup-game
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true 