services:
  - type: web
    name: turtle-soup-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true 